version: '3.3'

services:
  db:
    image: mysql/mysql-server:5.7
    container_name: monolithic_db
    ports:
      - "4306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=mobility
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--skip-character-set-client-handshake"]
